### ISSUE TITLE
Adjustments to User Experience

### ISSUE THREAD

**Issue by lauriemarkle** [IDEMSInternational/washtext#2]
For WASHText there is no pre/post question or troubleshooting support. Please remove these from the user experience.

**Comment by lauriemarkle** [comment]
- From onboarding, remove consent, queries for child name, child gender, child age, parent gender, parent name (these will be captured during baseline flow)
- Retain Parent First Name and Last Name
- Retain delivery of course certificate. 
- Provide the same delivery settings as Mexico in the 5 UX testing where users cannot access the progress tracker with visibility on other courses.

**Comment by fagiothree** [comment]
adjustments defined in https://docs.google.com/spreadsheets/d/1TJ1YVSu87ubc5GvGea2hfRh4v234OyJUccQnZ90VUP4/edit#gid=1270849835
